### ISSUE TITLE
Add SBOM generator

### ISSUE THREAD

**Issue by sydseter** [OWASP/cornucopia#1230]
This will probably be required at some point.

We may need to generate three of them, not sure, seeing that we have the card converter, the website, and the game engine.

**Comment by rewtd** [comment]
We can use https://github.com/CycloneDX/cdxgen-action to generate all the SBOMs I think.

- Game engine (copi) == Elixir ✅ 
- Website == Node ✅ 
- Card converter == Python ✅

**Comment by sydseter** [comment]
We need to make sure we release it as well: https://github.com/OWASP/cornucopia/actions/runs/18412255568/job/52467450543

**Comment by sydseter** [comment]
It’s only creating sbom for the card converter so we need to look at that as well. 

[bom.xml](https://github.com/user-attachments/files/22856610/bom.xml)
[reports.zip](https://github.com/user-attachments/files/22856612/reports.zip)

**Comment by sydseter** [comment]
Instead of the upload-artifact step we can try this:


```

- name: Add file to existing release
   uses: softprops/action-gh-release@v2 
   if: startsWith(github.ref, 'refs/tags/')
     with:
       files: reports

```

Then trigger the dependency report generation when a release tag is pushed.

```

on:
  push:
      tags:
          - "v*"
          - pre-release

```
